# beets config

# music directory
directory: ~/ct/music/imported-music

# music library
library: ~/.local/share/musiclibrary.db

# import settings
import:
  copy: yes
  write: yes
  log: ~/.local/share/beetslog.txt
  resume: yes
  incremental: yes
  incremental_skip_later: yes

# plugins
plugins: fetchart embedart lyrics lastgenre ftintitle fromfilename convert scrub missing

# fetchart plugin
fetchart:
  minwidth: 500
  sources: filesystem coverart itunes amazon albumart wikipedia google

# embedart plugin
embedart:
  remove_art_file: yes

# lyrics plugin
lyrics:
  force: yes
  sources: genius lyricwiki musixmatch 

# ui for the commandline
ui:
  color: yes
  colors:
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: red
    text_highlight_minor: lightgray
    action_default: turquoise
    action: blue

# path formats
paths:
  default: $albumartist/$album/$track $title
  singleton: Singles/$artist - $title
  comp: Various Artists/$album/$track $title
asciify_paths: yes
